### ISSUE TITLE
Backport PR does not trigger workflows

### ISSUE THREAD

**Issue by R0Wi** [tibdex/backport#55]
Hi, first thanks for this amazing Github action, it makes things much easier :-)

Today i first tried out the backport action and i encountered a strange issue: i merged a pull request into the `master` which was labeled with `backport stable20`. After the merge was done the action created a backport pull request as expected which points to `stable20`. Unfortunately the Github actions for running CI tests aren't triggered by this pull request even if they have a `pull_request` trigger set.

I created a minimal sample to demonstrate this:
* The [original pull request](https://github.com/R0Wi/github-action-testrepo/pull/3) (where the CI action was triggered)
* The [created pull request](https://github.com/R0Wi/github-action-testrepo/pull/4) by the backport action (where the CI action was **not** triggered)

<details><summary>My backport.yml</summary>
<p>

```yml
name: Backport
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-18.04
    name: Backport
    steps:
      - name: Backport
        uses: tibdex/backport@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

</p>
</details>

<details><summary>My "CI test"</summary>
<p>

```yml
name: Unittest

on:
  pull_request:
  push:
    branches:
      - master
      - stable*


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        shell: bash
        run: |
          echo "This is a testrun"
```

</p>
</details>

Did you encounter any similar issues or am i configuring anything wrong here? 

Thanks for your feedback !

**Comment by tibdex** [comment]
Hi Robin, thanks for the kind words.

This sounds like [this issue](https://github.community/t/triggering-a-new-workflow-from-another-workflow/16250).

Have you tried [github-app-token](https://github.com/marketplace/actions/github-app-token)?

**Comment by R0Wi** [comment]
Hi Thibault, thank you for your answer. 

I heard about something that a Github action cannot trigger another Github with the default `GITHUB_TOKEN` but i didn't realize that creating a pull request by the backport action is affected by this. To be honest i did not really understand how `github-app-token` works and if i can use it since i'm not using any Github apps at all.

But i was able to get things working by simply using a personal token instead of the `GITHUB_TOKEN` for the backport action. So basically i created a [personal access token](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token) with permissions to `public_repo` and created a new [secret ](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository)(`PERSONAL_TOKEN`) in my repository with the content of the token. So now my working Github actions looks like this:

```yaml
name: Backport
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-18.04
    name: Backport
    steps:
      - name: Backport
        uses: tibdex/backport@v1
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
```

Thanks again :-)
